### ISSUE TITLE
Tratamientos-Modificar

### ISSUE THREAD

**Issue by HannaPas** [HannaPas/TP-DhermaPixel#11]
Modificar la pagina de tratamientos para que solo contenga precios y nombre de los tratamientos (tarjetas con imágenes). 
SE PODRIA CONTENER ALGUNA DESCRIPCIÓN PERO BREVE SOBRE EL TRATAMIENTO O SEGUIR LA IDEA DE LO REALIZADO EN FIGMA

**Comment by EstebanChimbo** [comment]
Modificada la pagina de tratamientos, ya no tiene descripcion, solo cantidad de sesiones y precio, parecido al voceto de figma
